#!/usr/bin/env bash
# migrate-doc-lifecycle.sh — one-time, git-mv-driven migration to the ADR-087 doc-lifecycle
# taxonomy ("location is status; one root; everything moves"). Dry-run by DEFAULT.
#
# ADR-087 D1/D2/D4. The tree and its tooling move atomically: the tooling path constants are
# already updated in the SAME commit as this script (T3), so the intended steady state between
# "this commit lands" and "the operator runs --execute" is: tooling points NEW, tree still OLD.
# This script bridges that gap, ONCE, after operator review of the dry-run plan.
#
# Usage:
#   bash core/scripts/migrate-doc-lifecycle.sh            # DRY-RUN (default; prints the plan, mutates nothing)
#   bash core/scripts/migrate-doc-lifecycle.sh --dry-run  # same as default, explicit
#   bash core/scripts/migrate-doc-lifecycle.sh --execute   # PERFORMS the moves (git mv / git rm; stages only)
#
# Contract:
#   - DRY-RUN is the default. The operator reviews the full move plan BEFORE --execute.
#   - The script STAGES changes (git mv / git rm). It NEVER commits and NEVER pushes —
#     the operator/orchestrator commits after reviewing `git status`.
#   - Idempotent: re-running after a partial --execute must not error (missing sources are WARN+continue).
#   - Missing-source tolerant: every absent source logs a WARN and continues.
#   - Every action is echoed, one line per action (PLAN/MOVE/RM/MKDIR/WRITE/WARN/SKIP).
#
# History survives: git mv / git rm only — never a bare mv/rm of a tracked file.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
cd "$REPO_ROOT"

# ---- mode ----
MODE="dry-run"
case "${1:-}" in
  ""|--dry-run) MODE="dry-run" ;;
  --execute)    MODE="execute" ;;
  *) echo "migrate-doc-lifecycle: unknown arg '${1}' (use --dry-run | --execute)" >&2; exit 2 ;;
esac

DRY=true
[ "$MODE" = "execute" ] && DRY=false

# ---- counters (per action class) ----
declare -i N_MV=0 N_RM=0 N_MKDIR=0 N_WRITE=0 N_WARN=0 N_SKIP=0

# ---- emitters ----
# Each performs the action when executing; in dry-run it only prints the PLAN line.
log()  { echo "$@"; }
warn() { N_WARN+=1; echo "WARN: $*"; }
skip() { N_SKIP+=1; echo "SKIP: $*"; }

# git_mv <src> <dst>  — tolerant: missing src => WARN; existing dst (already migrated) => SKIP.
git_mv() {
  local src="$1" dst="$2"
  if [ ! -e "$src" ]; then
    # Idempotency: if the destination already exists, this move already happened — silent-ish skip.
    if [ -e "$dst" ]; then skip "already migrated: $dst (src $src absent)"; else warn "missing source (mv): $src"; fi
    return 0
  fi
  if [ -e "$dst" ]; then
    warn "destination exists, not overwriting: $dst (src $src left in place)"
    return 0
  fi
  N_MV+=1
  echo "MOVE: $src -> $dst"
  if ! $DRY; then
    mkdir -p "$(dirname "$dst")"
    git mv -- "$src" "$dst" 2>/dev/null || { warn "git mv failed (untracked?), using plain mv: $src -> $dst"; mv -- "$src" "$dst"; git add -- "$dst" 2>/dev/null || true; }
  fi
}

# git_rm <path>  — tolerant: missing => SKIP (idempotent).
git_rm() {
  local p="$1"
  if [ ! -e "$p" ]; then skip "already removed: $p"; return 0; fi
  N_RM+=1
  echo "RM: $p"
  if ! $DRY; then
    git rm -q -- "$p" 2>/dev/null || { rm -f -- "$p"; }
  fi
}

# ensure_dir <dir>
ensure_dir() {
  local d="$1"
  if [ -d "$d" ]; then return 0; fi
  N_MKDIR+=1
  echo "MKDIR: $d"
  if ! $DRY; then mkdir -p "$d"; fi
}

# write_file <path> <<heredoc  — writes only when executing (idempotent: skips if present).
# Reads body from stdin.
write_file() {
  local p="$1"
  local body; body="$(cat)"
  if [ -e "$p" ]; then skip "exists, not rewriting: $p"; return 0; fi
  N_WRITE+=1
  echo "WRITE: $p"
  if ! $DRY; then
    ensure_dir "$(dirname "$p")" >/dev/null
    printf '%s\n' "$body" > "$p"
    git add "$p" 2>/dev/null || true
  fi
}

# strip a known prefix from a basename: strip_prefix <prefix> <basename>
strip_prefix() { printf '%s' "${2#$1}"; }

echo "=== migrate-doc-lifecycle.sh (ADR-087) — MODE: ${MODE} — root: ${REPO_ROOT} ==="
if $DRY; then
  echo "    DRY-RUN: no mutations. Review the plan below, then re-run with --execute."
fi
echo ""

# ============================================================================
# Action 1 — step-1-ideas -> step-1-backlog (+ prefix handling)
#   - RAW-<date>-x.md       -> step-1-backlog/<date>-x.md   (strip RAW-)
#   - SHAPING-<date>-x.md    -> step-1-backlog/<date>-x.md   (strip SHAPING-; jam membership is the new signal)
#   - PROMOTED-*.md          -> per forward pointer if parseable, else step-2-planning/ + WARN
#   - DROPPED-*.md           -> git rm (git is the archive)
#   - INDEX.md               -> regenerated by idea-map.py later; drop the stale one (git rm)
#   - README.md              -> rewritten as step-1-backlog/README.md (see below)
# ============================================================================
echo "--- Action 1: step-1-ideas -> step-1-backlog (ideas; prefix retirement) ---"
IDEAS_DIR="docs/step-1-ideas"
BACKLOG_DIR="docs/step-1-backlog"
ensure_dir "$BACKLOG_DIR"
if [ -d "$IDEAS_DIR" ]; then
  while IFS= read -r f; do
    [ -z "$f" ] && continue
    base="$(basename "$f")"
    case "$base" in
      README.md|INDEX.md) continue ;;  # handled explicitly below
      RAW-*)
        git_mv "$f" "$BACKLOG_DIR/$(strip_prefix 'RAW-' "$base")" ;;
      SHAPING-*)
        git_mv "$f" "$BACKLOG_DIR/$(strip_prefix 'SHAPING-' "$base")" ;;
      PROMOTED-*)
        # Try to parse a forward pointer (shaped workspace / next step → a step-2/step-3 path).
        ptr="$(grep -oE 'docs/(step-2-planning|step-3-specs)/[A-Za-z0-9._/-]+' "$f" 2>/dev/null | head -1)"
        case "$ptr" in *..*) warn "refusing traversal forward pointer in $base: $ptr"; ptr="" ;; esac  # SA-001
        if [ -n "$ptr" ] && [ -d "$(dirname "$ptr")" ]; then
          # pointer target's parent exists → move alongside it (drop the PROMOTED- prefix)
          git_mv "$f" "$(dirname "$ptr")/$(strip_prefix 'PROMOTED-' "$base")"
        else
          warn "PROMOTED with no parseable/live forward pointer: $base → step-2-planning/ (operator: re-home on /sweep)"
          git_mv "$f" "docs/step-2-planning/$(strip_prefix 'PROMOTED-' "$base")"
        fi ;;
      DROPPED-*)
        git_rm "$f" ;;
      *.md)
        # already-unprefixed idea (future state) — move verbatim
        git_mv "$f" "$BACKLOG_DIR/$base" ;;
      *)
        skip "non-md in ideas dir: $base" ;;
    esac
  done < <(find "$IDEAS_DIR" -maxdepth 1 -type f -name '*.md' 2>/dev/null | sort)
  # stale generated INDEX — regenerated by idea-map.py post-migration
  git_rm "$IDEAS_DIR/INDEX.md"
else
  warn "no $IDEAS_DIR (already migrated?)"
fi
echo ""

# ============================================================================
# Action 2 — merge docs/deferrals/ into the backlog
#   - OPEN-<date>-x.md   -> step-1-backlog/DEFER-<date>-x.md   (rename prefix; keeps the source pointer)
#   - FIXED-/DONE-/CLOSED-/TRIAGED-/DROPPED- (resolved) -> step-6-done/deferrals/  (verbatim, prefix kept)
#   - README.md          -> superseded; moved aside in Action 5
#   - step-1-ideas/README.md -> rewritten as step-1-backlog/README.md (Action 2b)
# ============================================================================
echo "--- Action 2: merge docs/deferrals/ into step-1-backlog (OPEN-→DEFER-; resolved→step-6-done) ---"
DEFERRALS_DIR="docs/deferrals"
DONE_DEFERRALS="docs/step-6-done/deferrals"
if [ -d "$DEFERRALS_DIR" ]; then
  ensure_dir "$DONE_DEFERRALS"
  while IFS= read -r f; do
    [ -z "$f" ] && continue
    base="$(basename "$f")"
    case "$base" in
      README.md) continue ;;   # superseded — handled in Action 5
      OPEN-*)
        git_mv "$f" "$BACKLOG_DIR/DEFER-$(strip_prefix 'OPEN-' "$base")" ;;
      FIXED-*|DONE-*|CLOSED-*|TRIAGED-*|DROPPED-*)
        git_mv "$f" "$DONE_DEFERRALS/$base" ;;
      *.md)
        warn "unrecognized deferral prefix, routing to backlog as DEFER-: $base"
        git_mv "$f" "$BACKLOG_DIR/DEFER-$base" ;;
      *)
        skip "non-md in deferrals dir: $base" ;;
    esac
  done < <(find "$DEFERRALS_DIR" -maxdepth 1 -type f -name '*.md' 2>/dev/null | sort)
else
  warn "no $DEFERRALS_DIR (already migrated?)"
fi
echo ""

# --- Action 2b: author the new step-1-backlog/README.md (rewritten per ADR-087) ---
echo "--- Action 2b: author step-1-backlog/README.md (ADR-087 inbox convention) ---"
# Retire the old ideas README (its content is superseded by the rewrite below).
git_rm "$IDEAS_DIR/README.md"
write_file "$BACKLOG_DIR/README.md" <<'BACKLOG_README'
# step-1-backlog — THE inbox (ideas + deferrals, one pool)

The single funnel for everything not yet clustered. **Location is status** (ADR-087): a file lives here
because it is unprocessed backlog; advancing it is a `git mv` to the next step folder, not a prefix rename.

## What lands here

| File shape | What it is |
|---|---|
| `<date>-<slug>.md` | An **idea** — proactive ("I want to build/try Z eventually"). No `RAW-` prefix; the folder says it is backlog. Written by `/idea`. |
| `DEFER-<date>-<slug>.md` | A **deferral** — reactive, parked *during* work. Keeps the one `DEFER-` prefix because it carries a source-run pointer. Written by `/defer`. |
| `FOLLOWUP-<spec-slug>.md` | An auto-minted **follow-up stub** for deltas against a locked spec (ADR-087 D6): delta count + one-line gists. Structurally unforgettable backlog. |

## The rules (ADR-087)

1. **Advancing = `git mv` to the next folder.** Idea ripens → `git mv` into `docs/step-2-planning/jam-<cluster>/`
   (clustering) or `docs/step-3-specs/` (a roadmap/wave). No `RAW-`/`SHAPING-`/`PROMOTED-` prefix dance — the
   in-file status line is informational only; the **folder is the status**.
2. **Dropped = `git rm`.** Git history is the archive (`git log --diff-filter=D`); there is no graveyard folder.
3. **Swept on demand** via `/sweep` (operator-resolved: no nagging). Every item gets a verdict —
   promote / park / drop / keep / a reconciliation route.

Per-idea / per-deferral schema lives in the `/idea` and `/defer` skills. `INDEX.md` here is generated
(`core/scripts/idea-map.py`) and disposable.

> Supersedes the old `docs/step-1-ideas/README.md` (RAW-/PROMOTED-/DROPPED- prefix-as-status) and the
> standalone `docs/deferrals/` silo. See `docs/decisions/ADR-087-doc-lifecycle-location-is-status.md`.
BACKLOG_README
echo ""

# ============================================================================
# Action 3 — session-logs -> step-6-done/sessions
# ============================================================================
echo "--- Action 3: step-2-planning/session-logs -> step-6-done/sessions ---"
SESSLOGS_SRC="docs/step-2-planning/session-logs"
SESSLOGS_DST="docs/step-6-done/sessions"
if [ -d "$SESSLOGS_SRC" ]; then
  ensure_dir "$SESSLOGS_DST"
  # Move the whole directory's contents (preserve filenames, incl. _index.md).
  while IFS= read -r f; do
    [ -z "$f" ] && continue
    git_mv "$f" "$SESSLOGS_DST/$(basename "$f")"
  done < <(find "$SESSLOGS_SRC" -maxdepth 1 -type f 2>/dev/null | sort)
  # remove the now-empty source dir (untracked-empty is fine; git ignores empty dirs)
  if ! $DRY; then rmdir "$SESSLOGS_SRC" 2>/dev/null || true; fi
else
  warn "no $SESSLOGS_SRC (already migrated or never existed?)"
fi
echo ""

# ============================================================================
# Action 4 — sweep COMPLETED run folders -> step-6-done/<date>/
#   CONSERVATIVE: only move a run folder when its completion is explicit —
#     run-manifest.json status ∈ {complete, done}  OR  run-log.md contains a completion marker.
#   Otherwise leave in place and list as SKIPPED with reason.
#   Executed PENDING handoffs (status line EXECUTED/COMPLETE) -> step-6-done/handoffs/.
#   APPROVED-but-in-flight handoffs STAY in PENDING/.
# ============================================================================
echo "--- Action 4: sweep COMPLETED run folders -> step-6-done/<date>/ (conservative) ---"
PIPELINE_DIR="docs/step-5-pipeline"
DONE_DIR="docs/step-6-done"
# Completion markers in run-log.md (anchored, case-insensitive). Conservative: an explicit
# status/heading line, NOT a passing mention.
RUNLOG_DONE_RE='(^|[[:space:]])(status:[[:space:]]*)?(complete|completed|done|merged to main|wave done|run complete|wrapped up)([[:space:]]|$|\.)'
if [ -d "$PIPELINE_DIR" ]; then
  while IFS= read -r datedir; do
    [ -z "$datedir" ] && continue
    dname="$(basename "$datedir")"
    case "$dname" in
      PENDING) continue ;;   # handled below, not a date folder
    esac
    # Only treat YYYY-MM-DD dirs as run-date buckets.
    printf '%s' "$dname" | grep -qE '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' || { skip "non-date dir under pipeline: $dname"; continue; }
    while IFS= read -r runfolder; do
      [ -z "$runfolder" ] && continue
      rbase="$(basename "$runfolder")"
      mani="$runfolder/run-manifest.json"
      rlog="$runfolder/run-log.md"
      done_signal=""
      if [ -f "$mani" ] && grep -qiE '"status"[[:space:]]*:[[:space:]]*"(complete|done)"' "$mani" 2>/dev/null; then
        done_signal="manifest-status"
      elif [ -f "$rlog" ] && grep -qiE "$RUNLOG_DONE_RE" "$rlog" 2>/dev/null; then
        done_signal="run-log-marker"
      fi
      if [ -n "$done_signal" ]; then
        git_mv "$runfolder" "$DONE_DIR/$dname/$rbase"
      else
        skip "run not provably complete (no manifest/run-log completion signal): $dname/$rbase"
      fi
    done < <(find "$datedir" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | sort)
    # If the date dir is now empty after moves, drop it.
    if ! $DRY; then rmdir "$datedir" 2>/dev/null || true; fi
  done < <(find "$PIPELINE_DIR" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | sort)

  # Executed PENDING handoffs -> step-6-done/handoffs/
  PENDING_DIR="$PIPELINE_DIR/PENDING"
  DONE_HANDOFFS="$DONE_DIR/handoffs"
  if [ -d "$PENDING_DIR" ]; then
    ensure_dir "$DONE_HANDOFFS"
    while IFS= read -r hf; do
      [ -z "$hf" ] && continue
      hbase="$(basename "$hf")"
      case "$hbase" in
        README.md) continue ;;
        COMPLETE-*|RESULT-*|SUPERSEDED-*)
          # filename already declares it executed/superseded
          git_mv "$hf" "$DONE_HANDOFFS/$hbase" ;;
        handoff-*)
          # in-file status line: EXECUTED/COMPLETE -> done; APPROVED/in-flight -> STAY
          if grep -qiE '^\*\*Status:\*\*.*(EXECUTED|COMPLETE|DONE|SHIPPED)' "$hf" 2>/dev/null; then
            git_mv "$hf" "$DONE_HANDOFFS/$hbase"
          else
            skip "PENDING handoff in-flight/approved (stays): $hbase"
          fi ;;
        *)
          skip "unrecognized PENDING file (stays): $hbase" ;;
      esac
    done < <(find "$PENDING_DIR" -maxdepth 1 -type f 2>/dev/null | sort)
  else
    warn "no $PENDING_DIR"
  fi
else
  warn "no $PIPELINE_DIR"
fi
echo ""

# ============================================================================
# Action 5 — superseded convention docs -> step-6-done/superseded/ (with a tombstone)
# ============================================================================
echo "--- Action 5: superseded convention docs -> step-6-done/superseded/ ---"
SUPERSEDED_DIR="docs/step-6-done/superseded"
OLD_DEFERRALS_README="$DEFERRALS_DIR/README.md"
if [ -e "$OLD_DEFERRALS_README" ]; then
  ensure_dir "$SUPERSEDED_DIR"
  git_mv "$OLD_DEFERRALS_README" "$SUPERSEDED_DIR/README-deferrals.md"
  # Prepend a one-line tombstone pointing at ADR-087 (only on execute; in dry-run, just announce it).
  if ! $DRY && [ -e "$SUPERSEDED_DIR/README-deferrals.md" ]; then
    tomb="$SUPERSEDED_DIR/README-deferrals.md"
    { echo "> **SUPERSEDED by ADR-087** (doc lifecycle: location is status). The deferrals silo merged into \`docs/step-1-backlog/\` (\`OPEN-\`→\`DEFER-\`). Kept for history only — see \`docs/decisions/ADR-087-doc-lifecycle-location-is-status.md\`."; echo ""; cat "$tomb"; } > "${tomb}.tmp" && mv "${tomb}.tmp" "$tomb"
    git add "$tomb" 2>/dev/null || true
    echo "WRITE: prepended ADR-087 tombstone to $tomb"
  else
    echo "PLAN: prepend ADR-087 tombstone to $SUPERSEDED_DIR/README-deferrals.md"
  fi
else
  skip "no old deferrals README to supersede"
fi
echo ""

# ============================================================================
# Action 6 — create the parked/ shelf
# ============================================================================
echo "--- Action 6: create docs/parked/ (operator-only shelf) ---"
PARKED_DIR="docs/parked"
ensure_dir "$PARKED_DIR"
# .gitkeep so the empty shelf is tracked
if [ ! -e "$PARKED_DIR/.gitkeep" ]; then
  N_WRITE+=1; echo "WRITE: $PARKED_DIR/.gitkeep"
  if ! $DRY; then : > "$PARKED_DIR/.gitkeep"; git add "$PARKED_DIR/.gitkeep" 2>/dev/null || true; fi
else
  skip "exists: $PARKED_DIR/.gitkeep"
fi
write_file "$PARKED_DIR/README.md" <<'PARKED_README'
# parked — the operator's "not now" shelf

The visible top-level shelf for work the operator has deliberately set aside (ADR-087 D2.4).

- **Operator-only authority.** Agents may PROPOSE parking; only the operator's go moves a file in here.
- **Stage memory is kept** in the filename (`<stage-prefix>-<file>`) so unparking is a move-back to the
  stage it came from.
- One folder to scan answers "what did I shelve?" — `ls docs/parked/`.
- Swept on demand via `/sweep` alongside `docs/step-1-backlog/`.

See `docs/decisions/ADR-087-doc-lifecycle-location-is-status.md`.
PARKED_README
echo ""

# ============================================================================
# Summary
# ============================================================================
echo "============================================================"
MODE_UC="$(printf '%s' "$MODE" | tr '[:lower:]' '[:upper:]')"
echo "MIGRATION ${MODE_UC} SUMMARY"
echo "  MOVE  (git mv): $N_MV"
echo "  RM    (git rm): $N_RM"
echo "  MKDIR         : $N_MKDIR"
echo "  WRITE         : $N_WRITE"
echo "  WARN          : $N_WARN"
echo "  SKIP          : $N_SKIP"
echo "------------------------------------------------------------"
if $DRY; then
  echo "DRY-RUN complete — NOTHING was changed. Review the plan above."
  echo "When satisfied, run:  bash core/scripts/migrate-doc-lifecycle.sh --execute"
  echo "MIGRATE-DOC-LIFECYCLE: DRY-RUN (moves=${N_MV} rms=${N_RM} warns=${N_WARN} skips=${N_SKIP})"
else
  echo "EXECUTE complete — changes are STAGED (git mv / git rm), NOT committed."
  echo "REMINDER: the operator reviewed the dry-run first. Now review 'git status' and commit yourself."
  echo "          This script never commits and never pushes."
  echo "MIGRATE-DOC-LIFECYCLE: EXECUTED (moves=${N_MV} rms=${N_RM} warns=${N_WARN} skips=${N_SKIP})"
fi
exit 0
