#!/usr/bin/env bash
# test-docs-index-build-status.sh — fixture-driven test for the BUILD-STATUS.md render arm (ADR-109, W1DLP-T6).
#
# Each sub-test runs against an isolated, git-init'd tempdir via --root. The harness NEVER mutates the live
# repo. Mirrors core/scripts/test-*.sh's idiom (seed → run → assert → rm -rf).
#
# Covers:
#   wire-to-consumer       running docs-index.py (real main()) writes docs/BUILD-STATUS.md (AC-014)
#   byte-identity          a second render is byte-identical modulo the date stamp; --check passes (AC-011)
#   built-vs-unmerged      a done/unmerged feature lands in built-but-unmerged; a queued one in still-to-build (AC-010)
#   no-new-script          no new *.py build-status script under core/scripts/ (AC-014)
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
DI="$REPO_ROOT/core/scripts/docs-index.py"

PASS=0
FAIL=0
pass() { echo "  PASS  $1"; PASS=$((PASS + 1)); }
fail() { echo "  FAIL  $1"; FAIL=$((FAIL + 1)); }

# seed_fleet -> prints a tempdir with a fleet manifest + readiness buckets, git-init'd.
seed_fleet() {
  local tmp; tmp="$(mktemp -d)"
  mkdir -p "$tmp/docs/step-5-pipeline/fleet" \
           "$tmp/docs/step-1-ideas/ready-to-build" \
           "$tmp/docs/step-1-ideas/needs-shaping" \
           "$tmp/docs/step-1-ideas/blocked-on-dependency"
  cat > "$tmp/docs/step-5-pipeline/fleet/launch-manifest.json" <<'JSON'
{"schema":"fleet-manifest/2","slug":"demo-fleet","features":[
  {"label":"feat-done","kind":"orchestrated","spec":"a.md","status":"done","branch":"feature/wave-feat-done"},
  {"label":"feat-queued","kind":"orchestrated","spec":"b.md","status":"queued","branch":"feature/wave-feat-queued"}
]}
JSON
  echo "an idea" > "$tmp/docs/step-1-ideas/ready-to-build/i1.md"
  echo "shape me" > "$tmp/docs/step-1-ideas/needs-shaping/n1.md"
  git -C "$tmp" init -q
  git -C "$tmp" add -A
  git -C "$tmp" -c user.email=t@t -c user.name=t commit -q -m seed
  echo "$tmp"
}

t_wire_to_consumer() {
  echo "[wire-to-consumer] real main() writes docs/BUILD-STATUS.md (AC-014)"
  local tmp; tmp="$(seed_fleet)"
  python3 "$DI" --root "$tmp" >/dev/null 2>&1
  [ -f "$tmp/docs/BUILD-STATUS.md" ] && pass "main() wrote docs/BUILD-STATUS.md" || fail "BUILD-STATUS.md not written by main()"
  [ -f "$tmp/docs/INDEX.md" ] && pass "main() also wrote docs/INDEX.md (same run)" || fail "INDEX.md not written"
  grep -q "Generated by .core/scripts/docs-index.py." "$tmp/docs/BUILD-STATUS.md" \
    && pass "BUILD-STATUS.md opens with the generated-by header" || fail "no generated-by header"
  rm -rf "$tmp"
}

t_byte_identity() {
  echo "[byte-identity] a second render is byte-identical modulo date; --check passes (AC-011)"
  local tmp; tmp="$(seed_fleet)"
  python3 "$DI" --root "$tmp" >/dev/null 2>&1
  cp "$tmp/docs/BUILD-STATUS.md" "$tmp/first.md"
  python3 "$DI" --root "$tmp" --check >/dev/null 2>&1 && pass "--check reports current after a write" || fail "--check stale right after a write"
  python3 "$DI" --root "$tmp" >/dev/null 2>&1
  python3 - "$tmp/first.md" "$tmp/docs/BUILD-STATUS.md" <<'PY'
import re,sys
norm=lambda s:re.sub(r"Generated \d{4}-\d{2}-\d{2}","Generated <date>",s)
a=norm(open(sys.argv[1]).read()); b=norm(open(sys.argv[2]).read())
sys.exit(0 if a==b else 1)
PY
  [ $? -eq 0 ] && pass "second render byte-identical (modulo date stamp)" || fail "second render differs"
  rm -rf "$tmp"
}

t_built_vs_unmerged() {
  echo "[built-vs-unmerged] done/unmerged → built-but-unmerged; queued → still-to-build (AC-010)"
  local tmp; tmp="$(seed_fleet)"
  python3 "$DI" --root "$tmp" >/dev/null 2>&1
  local bs="$tmp/docs/BUILD-STATUS.md"
  # feat-done (status done, branch never merged in this fresh repo) → built-but-unmerged section
  awk '/Built-but-unmerged/{f=1} /Still-to-build/{f=0} f' "$bs" | grep -q 'feat-done' \
    && pass "feat-done in built-but-unmerged" || fail "feat-done not in built-but-unmerged"
  awk '/Still-to-build/{f=1} /Merged \(landed/{f=0} f' "$bs" | grep -q 'feat-queued' \
    && pass "feat-queued in still-to-build" || fail "feat-queued not in still-to-build"
  grep -q 'ready-to-build | 1' "$bs" && pass "inbox readiness ready-to-build=1 surfaced" || fail "readiness not surfaced"
  rm -rf "$tmp"
}

t_no_new_script() {
  echo "[no-new-script] only docs-index.py matches build-status under core/scripts/*.py (AC-014)"
  local hits
  hits="$(cd "$REPO_ROOT" && git grep -lE 'build.?status' core/scripts/*.py 2>/dev/null)"
  [ "$hits" = "core/scripts/docs-index.py" ] && pass "only docs-index.py is a build-status py" \
    || { fail "unexpected build-status py files"; echo "    $hits"; }
}

run_all() {
  t_wire_to_consumer
  t_byte_identity
  t_built_vs_unmerged
  t_no_new_script
}

case "${1:-all}" in
  all) run_all ;;
  wire-to-consumer) t_wire_to_consumer ;;
  byte-identity) t_byte_identity ;;
  built-vs-unmerged) t_built_vs_unmerged ;;
  no-new-script) t_no_new_script ;;
  *) echo "unknown subcommand: $1" >&2; exit 2 ;;
esac

echo ""
echo "=== test-docs-index-build-status.sh: $PASS passed, $FAIL failed ==="
[ "$FAIL" -eq 0 ]
